-- MySQL Script generated by MySQL Workbench
-- Fri May  5 00:00:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco-digital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco-digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco-digital` DEFAULT CHARACTER SET utf8 ;
USE `banco-digital` ;

-- -----------------------------------------------------
-- Table `banco-digital`.`tipo_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`tipo_contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `descricao_detalhada_tipo_conta` TEXT(65535) NULL,
  `limite_extrato_mensal` INT NULL,
  `limite_valor_por_saque` INT NULL,
  `limite_quant_saque_diario` INT NULL,
  `limite_quant_saque_mes` INT NULL,
  `limite_valor_saque_diario` INT NULL,
  `limite_valor_saque_mes` INT NULL,
  `limite_valor_tranferencia_diario` INT NULL,
  `limite_valor_transferencia_mensal` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`limites_conta_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`limites_conta_pessoal` (
  `id` INT NOT NULL,
  `id_conta` INT NOT NULL,
  `limite_valor_saque_diario` INT NULL,
  `limite_valor_saque_mensal` INT NULL,
  `limite_valor_transferencia_diario` INT NULL,
  `limite_valor_trasnferencia_mensal` INT NULL,
  `limite_quant_saque_diario` INT NULL,
  `limite_quant_saque_mensal` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`historico_saque_deposito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`historico_saque_deposito` (
  `id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `tipo_operacao` BIT NOT NULL,
  `valor_oeracao` INT NOT NULL,
  `historico_saque_depositocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`historico_transferencias_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`historico_transferencias_envio` (
  `id` INT NOT NULL,
  `data/time` DATETIME NULL,
  `numero_agencia` INT NULL,
  `numero_conta` INT NULL,
  `valor_enviado` INT ZEROFILL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`bancos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `historico_transferencias_envio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `historico_transferencias_envio_id`),
  INDEX `fk_bancos_historico_transferencias_envio1_idx` (`historico_transferencias_envio_id` ASC) VISIBLE,
  CONSTRAINT `fk_bancos_historico_transferencias_envio1`
    FOREIGN KEY (`historico_transferencias_envio_id`)
    REFERENCES `banco-digital`.`historico_transferencias_envio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`historico_transferencias_recebimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`historico_transferencias_recebimento` (
  `id` INT NOT NULL,
  `data/time` DATETIME NULL,
  `numero_agencia_origem` INT NULL,
  `numero_conta_origem` INT NULL,
  `valor_recebido` INT ZEROFILL NULL,
  `bancos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `bancos_id`),
  INDEX `fk_historico_transferencias_recebimento_bancos1_idx` (`bancos_id` ASC) VISIBLE,
  CONSTRAINT `fk_historico_transferencias_recebimento_bancos1`
    FOREIGN KEY (`bancos_id`)
    REFERENCES `banco-digital`.`bancos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Tipo_Pessoa` CHAR(1) NULL,
  `Nome` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Cliente` CHAR(1) NULL,
  `Funcionário` CHAR(1) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Funcionário` (
  `idFuncionário` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `Matrícula` INT NULL,
  `Data_Cadastro` DATE NULL,
  `Dada_Adminissão` DATE NULL,
  `Data_Demissão` DATE NULL,
  `CTPS_Número` INT NULL,
  `CTPS_Serio` INT NULL,
  `CTPS_Data_Expedição` DATE NULL,
  `CTPS_UF` VARCHAR(45) NULL,
  `Observação` VARCHAR(255) NULL,
  PRIMARY KEY (`idFuncionário`),
  INDEX `fk_Funcionário_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionário_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `nome_pt` VARCHAR(60) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  `bacen` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `ibge` INT NOT NULL,
  `ddd` VARCHAR(50) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pais_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `banco-digital`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`cidade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(120) NULL,
  `ibge` INT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estado_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `banco-digital`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`bairros` (
  `id` INT NOT NULL,
  `nome` VARCHAR(120) NULL,
  `ibge` INT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bairros_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_bairros_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `banco-digital`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Endereço` (
  `idEndereço` INT NOT NULL,
  `Rua` VARCHAR(255) NULL,
  `Número` VARCHAR(255) NULL,
  `CEP` INT NULL,
  `bairros_id` INT NOT NULL,
  PRIMARY KEY (`idEndereço`, `bairros_id`),
  INDEX `fk_Endereço_bairros1_idx` (`bairros_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_bairros1`
    FOREIGN KEY (`bairros_id`)
    REFERENCES `banco-digital`.`bairros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`agencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`agencias` (
  `id` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `idFuncionário(Gerente)` INT NOT NULL,
  `idEndereço` INT NOT NULL,
  PRIMARY KEY (`id`, `idFuncionário(Gerente)`, `idEndereço`),
  INDEX `fk_agencias_Funcionário1_idx` (`idFuncionário(Gerente)` ASC) VISIBLE,
  INDEX `fk_agencias_Endereço1_idx` (`idEndereço` ASC) VISIBLE,
  CONSTRAINT `fk_agencias_Funcionário1`
    FOREIGN KEY (`idFuncionário(Gerente)`)
    REFERENCES `banco-digital`.`Funcionário` (`idFuncionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agencias_Endereço1`
    FOREIGN KEY (`idEndereço`)
    REFERENCES `banco-digital`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID do cadastro do nosso Cliente',
  `status` BIT NOT NULL COMMENT 'Status do Cliente. Caso o cliente esteja ativado, será 1(true). Caso contrário, será 0(false).\nOnde true = Ativado e false = Desativado.\n',
  `idPessoa` INT NOT NULL,
  `senha` TEXT(65535) NULL COMMENT 'Senha do cliente.\nA senha do cliente contem um hash ARGON2\nOBS: Todos os dados estarão criptografado pelo AES',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_clientes_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_agencia` INT NOT NULL,
  `numero_conta` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `senha` TEXT(65535) NULL,
  `saldo_atual` INT ZEROFILL NULL,
  `id_tipo_contas` INT NOT NULL,
  `id_limites_conta_pessoal` INT NOT NULL,
  `id_historico_depoisito` INT NOT NULL,
  `id_historico_transferencia_envio` INT NOT NULL,
  `id_historico_transferencia_recebido` INT NOT NULL,
  PRIMARY KEY (`id`, `id_agencia`, `id_cliente`, `id_tipo_contas`, `id_limites_conta_pessoal`, `id_historico_depoisito`, `id_historico_transferencia_envio`, `id_historico_transferencia_recebido`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `id_conta_UNIQUE` (`numero_conta` ASC) VISIBLE,
  INDEX `fk_contas_tipo_contas1_idx` (`id_tipo_contas` ASC) VISIBLE,
  INDEX `fk_contas_limites_conta_pessoal1_idx` (`id_limites_conta_pessoal` ASC) VISIBLE,
  INDEX `fk_contas_historico_saque_deposito2_idx` (`id_historico_depoisito` ASC) VISIBLE,
  INDEX `fk_contas_historico_transferencias_envio1_idx` (`id_historico_transferencia_envio` ASC) VISIBLE,
  INDEX `fk_contas_historico_transferencias_recebimento1_idx` (`id_historico_transferencia_recebido` ASC) VISIBLE,
  INDEX `fk_contas_agencias1_idx` (`id_agencia` ASC) VISIBLE,
  INDEX `fk_contas_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_contas_tipo_contas1`
    FOREIGN KEY (`id_tipo_contas`)
    REFERENCES `banco-digital`.`tipo_contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_limites_conta_pessoal1`
    FOREIGN KEY (`id_limites_conta_pessoal`)
    REFERENCES `banco-digital`.`limites_conta_pessoal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_historico_saque_deposito2`
    FOREIGN KEY (`id_historico_depoisito`)
    REFERENCES `banco-digital`.`historico_saque_deposito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_historico_transferencias_envio1`
    FOREIGN KEY (`id_historico_transferencia_envio`)
    REFERENCES `banco-digital`.`historico_transferencias_envio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_historico_transferencias_recebimento1`
    FOREIGN KEY (`id_historico_transferencia_recebido`)
    REFERENCES `banco-digital`.`historico_transferencias_recebimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_agencias1`
    FOREIGN KEY (`id_agencia`)
    REFERENCES `banco-digital`.`agencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `banco-digital`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Pessoa Física`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Pessoa Física` (
  `idPessoa Física` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `CPF` VARCHAR(255) NULL,
  `Nome` VARCHAR(255) NULL,
  `RG` VARCHAR(255) NULL,
  `Orgão_RG` VARCHAR(255) NULL,
  `Data_Emissão_RG` VARCHAR(255) NULL,
  `Data_Nascimento` VARCHAR(255) NULL,
  `Sexo` VARCHAR(255) NULL,
  `Nacionalidade` VARCHAR(255) NULL,
  `Naturalidade` VARCHAR(255) NULL,
  `Nome_Pai` VARCHAR(255) NULL,
  `Nome_Mãe` VARCHAR(255) NULL,
  PRIMARY KEY (`idPessoa Física`),
  INDEX `fk_Pessoa Física_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Física_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Pessoa Jurídica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Pessoa Jurídica` (
  `idPessoa Jurídica` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `CNPJ` VARCHAR(255) NULL,
  `Nome_Fantasia` VARCHAR(255) NULL,
  `Inscrição_Estadual` VARCHAR(255) NULL,
  `Inscrição_Municipal` VARCHAR(255) NULL,
  `Data_constituição` VARCHAR(255) NULL,
  PRIMARY KEY (`idPessoa Jurídica`),
  INDEX `fk_Pessoa Jurídica_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Jurídica_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Pessoa_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Pessoa_Telefone` (
  `idPessoa_Telefone` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `Telefone` VARCHAR(255) NULL,
  `WhatsApp` VARCHAR(255) NULL,
  PRIMARY KEY (`idPessoa_Telefone`),
  INDEX `fk_Pessoa_Telefone_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Telefone_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Gerente da  Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Gerente da  Conta` (
  `id_Contas` INT NOT NULL,
  `id_Funcionário` INT NOT NULL,
  PRIMARY KEY (`id_Contas`, `id_Funcionário`),
  INDEX `fk_contas_has_Funcionário_Funcionário1_idx` (`id_Funcionário` ASC) VISIBLE,
  INDEX `fk_contas_has_Funcionário_contas1_idx` (`id_Contas` ASC) VISIBLE,
  CONSTRAINT `fk_contas_has_Funcionário_contas1`
    FOREIGN KEY (`id_Contas`)
    REFERENCES `banco-digital`.`contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_has_Funcionário_Funcionário1`
    FOREIGN KEY (`id_Funcionário`)
    REFERENCES `banco-digital`.`Funcionário` (`idFuncionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco-digital`.`Endereço_da_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco-digital`.`Endereço_da_pessoa` (
  `idEndereço` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `Observação` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereço`, `idPessoa`),
  INDEX `fk_Endereço_do_cliente_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_cliente_Endereço1`
    FOREIGN KEY (`idEndereço`)
    REFERENCES `banco-digital`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_do_cliente_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `banco-digital`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
